<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'title',
        'content',
        'status',
    ];

    public function comments(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Comments::class);
    }

    protected static function booted(): void
    {
        parent::booted(); // TODO: Change the autogenerated stub

        static::creating(function ($post) {
            $post->status = 'draft';
        });

        static::updating(function ($post) {
            $post->status = 'draft';
        });

        static::deleting(function ($post) {
            $post->comments()->delete();
        });

        static::restoring(function ($post) {
            $post->comments()->restore();
        });

    }
}
